# Generated by Django 2.2.2 on 2021-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.IntegerField(default=0)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('ifsc_code', models.CharField(default='', max_length=20)),
                ('Branch', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=200)),
                ('District', models.CharField(default='', max_length=30)),
                ('State', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
